networks:
  asvsp-project:
    name: asvsp-project
    external: true
    
services:
  metabase-postgres:
    image: postgres:17.7
    container_name: mb-postgres
    hostname: mb-postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabasedb
      POSTGRES_PASSWORD: metabasepass
    volumes:
      - metabase-db-volume:/var/lib/postgresql/data
      - ./config:/config
    networks:
      - asvsp-project

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - ./data:/dev/random:ro
    ports:
      - 3000:3000
    depends_on:
      - metabase-postgres
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabasedb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabasepass
      MB_DB_HOST: mb-postgres
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - asvsp-project

volumes:
  metabase-db-volume: